# -*- coding: utf-8 -*-
"""MapReduce_Mrjob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJJC4B_fDkFc31W8LqHa1B41sMfXgxgf
"""

!python --version

!sudo apt-get update -y
!sudo apt-get install python3.10 python3.10-distutils -y

# 3. Point Colab to use Python 3.10
!sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
!sudo update-alternatives --config python

# 4. Install pip for Python 3.10
!curl -sS https://bootstrap.pypa.io/get-pip.py | python

# 5. Install mrjob
!pip install mrjob

!python wordcount.py input.txt

!python anomaly.py weather_classification_data.csv

!python mr_avg_temp.py GlobalWeatherRepository_kaggle.csv > output.txt

!head output.txt

import pandas as pd

results = pd.read_csv("output.txt", sep="\t", header=None, names=["country", "avg_temp"])
results.sort_values("avg_temp", ascending=False).head(10)